name: Races
main: de.tobiyas.races.Races
version: 0.1
website: http://
author: tobiyas

softdepends: [Vault]
description: >
             Races for Players
commands:
  race:
    description: Sets the Race of the player
    aliases: []
    usage: |
           /race <racename>
  racechat:
    description: chat for the race
    aliases: [rc,rchat]
    usage: |
           /racechate <message>
  raceinfo:
    description: info for races
    aliases: [rinfo]
    usage: |
           /raceinfo
  racehelp:
    description: help for races
    aliases: [rhelp]
    usage: |
           /racehelp <helpstring>
  racelist:
    description: lists all races
    aliases: [rlist]
    usage: |
           /racelist
  whisper:
    description: whispers a Player
    aliases: [w]
    usage: |
           /whisper <player> <message>
  traitlist:
    description: lists all traits
    aliases: [tlist]
    usage: |
           /traitlist
  raceheal:
    description: heals a player
    aliases: [rheal,rh]
    usage: |
           /raceheal [PlayerName]
  raceconfig:
    description: changes the config of a player
    aliases: [rconfig]
    usage: |
           /raconfig <attribute> <value>
  racedebug:
    description: debug stuff
    aliases: [rdebug]
    usage: |
           /racedebug [option] [value]