name: Races
main: de.tobiyas.races.Races
version: 0.07
website: http://
author: tobiyas

softdepends: [Vault]
description: >
             Races for Players
commands:
  race:
    description: Sets the Race of the player
    aliases: []
    usage: |
           /race <racename>
  racechat:
    description: chat for the race
    aliases: [rc,rchat]
    usage: |
           /racechate <message>
  racehelp:
    description: help for races
    aliases: [rhelp]
    usage: |
           /racehelp <helpstring>
  whisper:
    description: whispers a Player
    aliases: [w]
    usage: |
           /whisper <player> <message>
  traitlist:
    description: lists all traits
    aliases: [tlist]
    usage: |
           /traitlist
  raceheal:
    description: heals a player
    aliases: [rheal,rh]
    usage: |
           /raceheal [PlayerName]
  raceconfig:
    description: changes the config of a player
    aliases: [rconfig]
    usage: |
           /raconfig <attribute> <value>
  racedebug:
    description: debug stuff
    aliases: [rdebug]
    usage: |
           /racedebug [option] [value]
  class:
    description: changes/selectes a class
    aliases: []
    usage: |
           /class <select,change> <classname>
  playerhealth:
    description: displays your HP
    aliases: [hp]
    usage: |
           /hp
  racesreload:
    description: reloads everything
    aliases: []
    usage: |
           /racereload
  channel:
    description: manages channels
    aliases: []
    usage: |
           /channel
  racegod:
    description: switches god mode to player
    aliases: [rgod]
    usage: |
           /racegod [playername]
  globalbroadcast:
    description: broadcasts a message to all Players in Global channel.
    aliases: [gbr]
    usage: |
           /globalbroadcast <message>
  localchat:
    description: sends a message to local chat
    aliases: [lc,l]
    usage: |
           /<command> message
  racesversion:
    description: displays the full version of Races
    aliases: []
    usage: |
           /<command>